### ISSUE TITLE
More indexes lack and 'end-page' column

### ISSUE THREAD

**Issue by lsiden** [aspiers/book-indices#26]
The following indexes need an 'end-page' column:

ColoBk.csv
EvansBk.csv
JazzFake.csv
JazzLTD.csv
Library.csv
NewReal1.csv
NewReal2.csv
NewReal3.csv
RealBk1.csv
RealBk2.csv
RealBk3.csv

**Comment by aspiers** [comment]
These were deliberately omitted because I wrote code which allows them to be optional by automatically inferring the end page from the next start page:

https://github.com/aspiers/PDFexploder/blob/f33fc23b14c4f171073d776a13c298c43cfcea21/lib/book.rb#L117-L130

However, it doesn't do any harm to add them, and I guess this would help any other software using the same indices, so I'll gladly merge #27.
